# Generated by Django 3.1.2 on 2020-10-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_auto_20201030_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='officesupply',
            name='manufacturer',
            field=models.BooleanField(default=False, verbose_name='Наличие производителя'),
        ),
        migrations.AddField(
            model_name='officesupply',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Производитель'),
        ),
    ]
